name: 'Serverless with Python Requirements'
description: 'Javascript action that runs a Serverless deploy using the serverless-python-requirements plugin.'
inputs:
  args:
    default: ''
    description: 'Additional arguments you want to set'
    required: false
  aws-access-key-id:
    description: 'Your aws access key id'
    required: false
  aws-secret-access-key:
    description: 'Your aws secret access key'
    required: false
  serverless-access-key:
    default: ''
    description: 'Your serverless access key'
    required: false

runs:
  using: 'node12'
  main: 'index.js'

branding:
  icon: 'fast-forward'
  color: 'red'